name: Run Minecraft Bot

on:
  schedule:
    - cron: '*/15 * * * *'     # Every 15 minutes
    - cron: '10 */6 * * *'     # Every 6 hours at 10 min past the hour
  workflow_dispatch:           # Manual trigger button on GitHub

concurrency:
  group: run-minecraft-bot
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: timeout 350m node bot.js
